# Generated by Django 5.2.9 on 2025-12-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VisitedLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('level', models.IntegerField(choices=[(0, 'Country'), (1, 'State'), (2, 'District')])),
                ('parent', models.CharField(blank=True, max_length=255, null=True)),
                ('grandparent', models.CharField(blank=True, max_length=255, null=True)),
                ('marked_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
