# Generated by Django 5.2.9 on 2025-12-07 13:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='visitedlocation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visited_locations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='visitedlocation',
            index=models.Index(fields=['user', 'level'], name='locations_v_user_id_4551d1_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='visitedlocation',
            unique_together={('user', 'name', 'level', 'parent')},
        ),
    ]
