# Generated by Django 5.2.9 on 2025-12-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DistrictPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district_name', models.CharField(max_length=255)),
                ('state_name', models.CharField(max_length=255)),
                ('country_name', models.CharField(max_length=255)),
                ('photo_url', models.URLField()),
                ('cloudinary_public_id', models.CharField(max_length=255)),
                ('file_size_bytes', models.IntegerField()),
                ('caption', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
